app = '<APP_NAME>'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 4

[mounts]
  source = "data"
  destination = "/data"
  initial_size = "100gb"